### ISSUE TITLE
license 问题

### ISSUE THREAD

**Issue by Maple13** [ckinmind/apple-basket-redux#17]
您好! 近期在学习redux 中找到您的项目 , 参考了您项目中的苹果🍎游戏中的代码, 但您在 package.json 中并未明确 license , 所以想问下您是否可以使用您的代码作为 demo, 请明确 license 吧

**Comment by ckinmind** [comment]
@Maple13 已加license, 你可以随意使用

**Comment by Maple13** [comment]
谢谢
